# https://wildwolf.name/github-actions-how-to-avoid-running-the-same-workflow-multiple-times/
name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  prepare:

    runs-on: ubuntu-latest
    outputs:
      head_tag: ${{ steps.check.outputs.head_tag }}
      foreign_pr: ${{ steps.check.outputs.foreign_pr }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Retrieve tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Set output variables
        id: check
        run: |
          fpr="no"
          tag=""
          if [[ "${{ github.ref }}" == refs/heads/* ]]; then
            tag="$(git tag --points-at HEAD)"
          elif [[ "${{ github.ref }}" == refs/pull/* ]] && [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.event.pull_request.base.repo.full_name }}" ]; then
            fpr="yes"
          fi
          echo "::set-output name=foreign_pr::${fpr}"
          echo "::set-output name=head_tag::${tag}"

  build:
    runs-on: ${{ matrix.os }}
    needs: prepare
    if: "(github.event_name == 'push' && needs.prepare.outputs.head_tag == '') || (github.event_name == 'pull_request' && needs.prepare.outputs.foreign_pr == 'yes')"
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Restore Node packages
        run: npm install

      - name: Compile
        run: npm run dist

      - name: Upload all artifacts
        uses: actions/upload-artifact@v2.3.1
        with:
          name: Build Artifacts
          path: "*.*" # Match all files, but not subfolders with unpacked builds
